---
- name: Verify
  hosts: all
  become: true

  tasks:
  post_tasks:
    - name: Check status to Zookeeper
      command: /opt/zookeeper/bin/zkServer.sh status
      register: zoo_status
      changed_when: false

    - name: Check service running
      fail:
        msg: "Zookeeper service not running"
      when:
        - "'Error contacting service. It is probably not running.' in zoo_status.stdout"

    - name: Check mode status
      fail:
        msg: "Zookeeper mode is not standalone"
      when:
        - "'Mode: standalone' not in zoo_status.stdout"
