---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: instance-ubuntu-1
    image: "percygrunwald/docker-ubuntu1804-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
     - zookeeper
  - name: instance-ubuntu-2
    image: "percygrunwald/docker-ubuntu1804-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
     - zookeeper
  - name: instance-ubuntu-3
    image: "percygrunwald/docker-ubuntu1804-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
     - zookeeper

  - name: instance-RHEL-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - zookeeper
  - name: instance-RHEL-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - zookeeper
  - name: instance-RHEL-3
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - zookeeper
provisioner:
  name: ansible
  log: false
  options:
    vvv: false
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:

      instance-RHEL-1:
        zookeeper_id: 1
      instance-RHEL-2:
        zookeeper_id: 2
      instance-RHEL-3:
        zookeeper_id: 3

      instance-ubuntu-1:
        zookeeper_id: 1
      instance-ubuntu-2:
        zookeeper_id: 2
      instance-ubuntu-3:
        zookeeper_id: 1
scenario:
  name: cluster
verifier:
  name: ansible
